package computermaker.impl;

import sorcer.service.Context;
import sorcer.service.ContextException;

import java.util.Locale;

public class ComputerParts {

    public static String PROCESSOR = "processor";
    public static String MEMORY = "memory";
    public static String HARD_DRIVE = "hardDrive";

    public Context getMemory(Context context) {
        return getFromContext(context, MEMORY);
    }

    public Context getHardDrive(Context context) {
        return getFromContext(context, HARD_DRIVE);
    }

    public Context getProcessor(Context context) {
        return getFromContext(context, PROCESSOR);
    }

    // stub function which take context and part to return context on the part generated by the implementation
    private Context getFromContext(Context context, String part) {
        try {
            context.setReturnValue(part.toLowerCase(Locale.ROOT));
        } catch (ContextException e) {
            e.printStackTrace();
        }
        return context;
    }


}
